name: vr_local_app
description: "A new Flutter project for local services."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  #share_plus: ^10.1.2
  url_launcher: ^6.3.0
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.2.0
 #permission_handler: ^11.3.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.5
  #speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true