// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMqwm_-KXcRe8YqAagarsBBsc_lh0G4G0',
    appId: '1:899887915588:web:ed4c679955e2a9112a9211',
    messagingSenderId: '899887915588',
    projectId: 'localservicesapp-9cc3e',
    authDomain: 'localservicesapp-9cc3e.firebaseapp.com',
    storageBucket: 'localservicesapp-9cc3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbNL5IvuThBVnzhAhVry4lBZvhjoisA4c',
    appId: '1:899887915588:android:34fb7d356ea7be6e2a9211',
    messagingSenderId: '899887915588',
    projectId: 'localservicesapp-9cc3e',
    storageBucket: 'localservicesapp-9cc3e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMqwm_-KXcRe8YqAagarsBBsc_lh0G4G0',
    appId: '1:899887915588:web:367542d8570c6fcf2a9211',
    messagingSenderId: '899887915588',
    projectId: 'localservicesapp-9cc3e',
    authDomain: 'localservicesapp-9cc3e.firebaseapp.com',
    storageBucket: 'localservicesapp-9cc3e.firebasestorage.app',
  );
}
